SET NAMES UTF8;
DROP DATABASE IF EXISTS travel;
CREATE DATABASE travel CHARSET=UTF8;
USE travel;
CREATE TABLE t_user(
uid INT PRIMARY KEY AUTO_INCREMENT,
uname VARCHAR(32),
upwd VARCHAR(32),
sex INT,
tel VARCHAR(20),
email VARCHAR(100)
);
INSERT INTO t_user VALUES(null,'admin','admin',1,'12345678974','163978@163.com');